/* 自动生成，不要手改：node scripts/build-ce-style.js
   来源：../wxlh-game/css/style.css + ce-extra.css，按元素上下文算好的引擎样式表。
   生成时间：2026-09-16 11:11 */
module.exports = {
 "cur-chip": {
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 5,
  "paddingRight": 11,
  "paddingBottom": 5,
  "paddingLeft": 11,
  "minHeight": 40,
  "fontSize": 12,
  "color": "#e9edf6"
 },
 "card": {
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "text-rows": {
  "marginBottom": 14
 },
 "list-row": {
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 10,
  "paddingRight": 4,
  "paddingBottom": 10,
  "paddingLeft": 4,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "grow": {
  "flex": 1,
  "minWidth": 0
 },
 "t1": {
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "tag": {
  "fontSize": 11,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 1,
  "paddingRight": 6,
  "paddingBottom": 1,
  "paddingLeft": 6,
  "color": "#b6bfd0",
  "fontWeight": "normal"
 },
 "t2": {
  "fontSize": 11,
  "color": "#7a849b",
  "marginTop": 3
 },
 "btn": {
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 18,
  "paddingBottom": 0,
  "paddingLeft": 18,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "backgroundColor": "#161d2a",
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold"
 },
 "section-title": {
  "flexDirection": "row",
  "alignItems": "center",
  "fontSize": 12,
  "color": "#b6bfd0",
  "fontWeight": "bold",
  "letterSpacing": 1,
  "marginTop": 18,
  "marginRight": 4,
  "marginBottom": 10,
  "marginLeft": 4
 },
 "text-menu": {
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "tile": {
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 54,
  "paddingTop": 8,
  "paddingRight": 6,
  "paddingBottom": 8,
  "paddingLeft": 6,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 6,
  "borderTopLeftRadius": 6,
  "borderTopRightRadius": 6,
  "borderBottomRightRadius": 6,
  "borderBottomLeftRadius": 6,
  "color": "#e9edf6",
  "minWidth": 0
 },
 "hint": {
  "fontSize": 11,
  "color": "#7a849b"
 },
 "mt2": {
  "marginTop": 10
 },
 "grid-title": {
  "fontSize": 11,
  "color": "#7a849b",
  "letterSpacing": 2,
  "marginTop": 14,
  "marginRight": 2,
  "marginBottom": 10,
  "marginLeft": 2
 },
 "idle-card": {
  "paddingTop": 4,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14
 },
 "idle-line": {
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 6,
  "paddingRight": 0,
  "paddingBottom": 6,
  "paddingLeft": 0,
  "borderBottomWidth": 0,
  "borderBottomColor": "#ffffff0d",
  "flexWrap": "wrap"
 },
 "btn-row": {
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "nav-item": {
  "flex": 1,
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center",
  "color": "#7a849b",
  "fontSize": 11
 },
 "modal-mask": {
  "position": "absolute",
  "backgroundColor": "rgba(0,0,0,.62)"
 },
 "sheet": {
  "position": "absolute",
  "width": "100%",
  "maxWidth": 520,
  "maxHeight": "86%",
  "backgroundColor": "#0b0e15",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderBottomWidth": 0,
  "borderTopLeftRadius": 18,
  "borderTopRightRadius": 18,
  "borderBottomRightRadius": 0,
  "borderBottomLeftRadius": 0,
  "flexDirection": "column",
  "paddingBottom": 0,
  "left": "50%",
  "bottom": 0
 },
 "page": {
  "position": "absolute",
  "width": "100%",
  "maxWidth": 520,
  "backgroundColor": "#0b0e15",
  "flexDirection": "column",
  "top": 0,
  "bottom": 0,
  "left": "50%"
 },
 "back-x": {
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "padding": 0,
  "paddingTop": 0,
  "paddingRight": 0,
  "paddingBottom": 0,
  "paddingLeft": 0,
  "width": 40,
  "height": 40,
  "flex": 0,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "backgroundColor": "#111621",
  "color": "#b6bfd0",
  "fontSize": 20
 },
 "page-pad": {
  "width": 40,
  "flex": 0
 },
 "note": {
  "fontSize": 12,
  "color": "#7a849b"
 },
 "bar": {
  "height": 8,
  "backgroundColor": "#0d1120",
  "borderRadius": 6,
  "borderTopLeftRadius": 6,
  "borderTopRightRadius": 6,
  "borderBottomRightRadius": 6,
  "borderBottomLeftRadius": 6
 },
 "mt3": {
  "marginTop": 14
 },
 "kv": {
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "space-between",
  "fontSize": 13,
  "paddingTop": 5,
  "paddingRight": 0,
  "paddingBottom": 5,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "mb2": {
  "marginBottom": 10
 },
 "b-field": {
  "flex": 1,
  "flexDirection": "column",
  "paddingTop": 0,
  "paddingRight": 14,
  "paddingBottom": 0,
  "paddingLeft": 14
 },
 "b-row": {
  "flexDirection": "row",
  "justifyContent": "center",
  "flexWrap": "wrap"
 },
 "b-line-label": {
  "textAlign": "center",
  "fontSize": 11,
  "color": "#7a849b",
  "letterSpacing": 1
 },
 "b-controls": {
  "flexDirection": "column",
  "paddingTop": 0,
  "paddingRight": 14,
  "paddingBottom": 12,
  "paddingLeft": 14
 },
 "b-potions": {
  "flexDirection": "column",
  "marginBottom": 8
 },
 "chev": {
  "flex": 0,
  "alignSelf": "center",
  "color": "#7a849b",
  "fontSize": 16
 },
 "blk": {
  "width": "100%"
 },
 "world-card": {
  "flexDirection": "row",
  "alignItems": "center"
 },
 "world-ico": {
  "width": 52,
  "height": 52,
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "fontSize": 24,
  "backgroundColor": "#232c42",
  "borderWidth": 1,
  "borderColor": "#232b3b"
 },
 "pos-row-label": {
  "marginTop": 8,
  "marginRight": 2,
  "marginBottom": 6,
  "marginLeft": 2,
  "fontSize": 12,
  "fontWeight": "bold",
  "color": "#e9edf6",
  "flexDirection": "row",
  "alignItems": "center"
 },
 "party-slots": {
  "flexDirection": "row"
 },
 "pslot": {
  "backgroundColor": "#161d2a",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "minHeight": 96,
  "padding": 10,
  "paddingTop": 10,
  "paddingRight": 10,
  "paddingBottom": 10,
  "paddingLeft": 10
 },
 "btn-grid3": {
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "mt1": {
  "marginTop": 4
 },
 "gold": {
  "color": "#e6b64c"
 },
 "empty": {
  "textAlign": "center",
  "color": "#7a849b",
  "fontSize": 13,
  "paddingTop": 30,
  "paddingRight": 0,
  "paddingBottom": 30,
  "paddingLeft": 0
 },
 "formation-list": {
  "marginTop": 8,
  "borderTopWidth": 1,
  "borderTopColor": "#232b3b"
 },
 "fm-row": {
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap",
  "fontSize": 11,
  "paddingTop": 6,
  "paddingRight": 0,
  "paddingBottom": 6,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff08",
  "opacity": 0.55
 },
 "pill-tabs": {
  "flexDirection": "row",
  "paddingBottom": 6
 },
 "pill": {
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 8,
  "paddingRight": 14,
  "paddingBottom": 8,
  "paddingLeft": 14,
  "minHeight": 44,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "fontSize": 12,
  "color": "#7a849b"
 },
 "filter-bar": {
  "flexDirection": "row",
  "alignItems": "center",
  "marginBottom": 8
 },
 "search-input": {
  "flex": 1,
  "minHeight": 44,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "color": "#e9edf6",
  "fontSize": 13,
  "paddingTop": 0,
  "paddingRight": 12,
  "paddingBottom": 0,
  "paddingLeft": 12
 },
 "char-grid": {
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "grow-row": {
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 11,
  "paddingRight": 14,
  "paddingBottom": 11,
  "paddingLeft": 14
 },
 "tap": {},
 "tab-cards": {
  "flexDirection": "row",
  "paddingTop": 10,
  "paddingRight": 0,
  "paddingBottom": 10,
  "paddingLeft": 0,
  "marginBottom": 10,
  "backgroundColor": "#0b0e15f5"
 },
 "mb3": {
  "marginBottom": 14
 },
 "bg-head": {
  "flexDirection": "row",
  "alignItems": "center",
  "fontSize": 12,
  "marginBottom": 8
 },
 "bg-grid": {
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "bg-slot": {
  "minHeight": 62,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#00000022",
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "flex-start",
  "paddingTop": 5,
  "paddingRight": 6,
  "paddingBottom": 11,
  "paddingLeft": 6,
  "color": "#e9edf6",
  "textAlign": "center"
 },
 "eq-bar": {
  "flexDirection": "row",
  "alignItems": "center",
  "fontSize": 11,
  "color": "#7a849b"
 },
 "tt-dot": {
  "width": 6,
  "height": 6,
  "marginLeft": 4,
  "backgroundColor": "#d43a4f"
 },
 "view#app": {
  "maxWidth": 520,
  "marginTop": 0,
  "marginRight": 0,
  "marginBottom": 0,
  "marginLeft": 0,
  "minHeight": "100%",
  "backgroundColor": "#07090e",
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%",
  "height": "100%",
  "flexDirection": "column",
  "margin": 0
 },
 "view#app__view#topbar": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%",
  "maxWidth": 520,
  "backgroundColor": "rgba(7,9,14,.94)",
  "borderBottomWidth": 1,
  "borderBottomColor": "#232b3b",
  "paddingTop": 0,
  "flex": 0
 },
 "view#app__view#topbar__view.player-row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 10,
  "paddingRight": 14,
  "paddingBottom": 4,
  "paddingLeft": 14
 },
 "view#app__view#topbar__view.player-row__text.pname": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 10,
  "__textW": 45
 },
 "view#app__view#topbar__view.player-row__text.plv": {
  "color": "#e6b64c",
  "fontSize": 11,
  "borderWidth": 1,
  "borderColor": "#e6b64c66",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 0,
  "paddingRight": 6,
  "paddingBottom": 0,
  "paddingLeft": 6,
  "marginRight": 10,
  "__textW": 24
 },
 "view#app__view#topbar__view.player-row__view.tb-spacer": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "marginRight": 10
 },
 "view#app__view#topbar__view#curbar": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "paddingTop": 2,
  "paddingRight": 14,
  "paddingBottom": 10,
  "paddingLeft": 14
 },
 "view#app__view#topbar__view#curbar__view.cur-chip": {
  "color": "#e9edf6",
  "fontSize": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 5,
  "paddingRight": 11,
  "paddingBottom": 5,
  "paddingLeft": 11,
  "minHeight": 40,
  "marginRight": 6
 },
 "view#app__view#topbar__view#curbar__view.cur-chip__text.cur-ico.isxh5spr3": {
  "color": "#ffd76a",
  "fontSize": 12,
  "marginRight": 5,
  "__textW": 8
 },
 "view#app__view#topbar__view#curbar__view.cur-chip__text.cur-val": {
  "color": "#e9edf6",
  "fontSize": 12,
  "marginRight": 5,
  "__textW": 17
 },
 "view#app__view#topbar__view#curbar__view.cur-chip__text.cur-ico.isx1l3rubl": {
  "color": "#6ec6ff",
  "fontSize": 12,
  "marginRight": 5,
  "__textW": 8
 },
 "view#app__view#topbar__view#curbar__view.cur-chip__text.cur-ico.isxh4wp74": {
  "color": "#ff9ecb",
  "fontSize": 12,
  "marginRight": 5,
  "__textW": 8
 },
 "view#app__view#topbar__view#curbar__view.cur-chip.more": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 5,
  "paddingRight": 11,
  "paddingBottom": 5,
  "paddingLeft": 11,
  "minHeight": 40,
  "marginRight": 6
 },
 "view#app__view#topbar__view#curbar__view.cur-chip.more__text.cur-val": {
  "color": "#7a849b",
  "fontSize": 12,
  "marginRight": 5,
  "__textW": 77
 },
 "view#app__scrollview#view": {
  "color": "#e9edf6",
  "fontSize": 15,
  "paddingTop": 0,
  "paddingRight": 0,
  "paddingBottom": 0,
  "paddingLeft": 0,
  "flex": 1,
  "flexShrink": 1,
  "padding": 0
 },
 "view#app__scrollview#view__view.screen": {
  "color": "#e9edf6",
  "fontSize": 15,
  "paddingTop": 6,
  "paddingRight": 12,
  "paddingBottom": 14,
  "paddingLeft": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows__view.row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 7,
  "paddingRight": 0,
  "paddingBottom": 7,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows__view.row__text.rk": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "marginRight": 10,
  "__textW": 48
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows__view.row__text.isxwtv0ps.rv": {
  "color": "#d43a4f",
  "fontSize": 13,
  "flex": 1,
  "textAlign": "right",
  "fontWeight": "bold",
  "whiteSpace": "nowrap",
  "minWidth": 0,
  "maxWidth": "62%",
  "textOverflow": "ellipsis",
  "marginRight": 10,
  "__textW": 52
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows__view.row__text.rs": {
  "color": "#7a849b",
  "fontSize": 11,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 123
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows__view.row__text.rv": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flex": 1,
  "textAlign": "right",
  "fontWeight": "bold",
  "whiteSpace": "nowrap",
  "minWidth": 0,
  "maxWidth": "62%",
  "textOverflow": "ellipsis",
  "marginRight": 10,
  "__textW": 27
 },
 "view#app__scrollview#view__view.screen__view.card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "borderWidth": 0,
  "padding": 0,
  "paddingTop": 10,
  "paddingRight": 4,
  "paddingBottom": 10,
  "paddingLeft": 4,
  "flexDirection": "row",
  "alignItems": "center",
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__view.t1__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 115
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__view.t1__text.tag": {
  "color": "#b6bfd0",
  "fontSize": 11,
  "fontWeight": "normal",
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 1,
  "paddingRight": 6,
  "paddingBottom": 1,
  "paddingLeft": 6,
  "alignSelf": "center",
  "lineHeight": 15,
  "marginRight": 6,
  "__textW": 58
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__view.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__view.t2__text": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__view.t2__text.isxh5spr3": {
  "color": "#ffd76a",
  "fontSize": 11,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__text.btn.ghost.small": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "transparent",
  "fontWeight": "bold",
  "minWidth": 44,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "marginRight": 14,
  "__textW": 49
 },
 "view#app__scrollview#view__view.screen__text.section-title": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "fontWeight": "bold",
  "letterSpacing": 1,
  "marginTop": 18,
  "marginRight": 4,
  "marginBottom": 10,
  "marginLeft": 4,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.text-menu": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.text-menu__view.tile": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 54,
  "paddingTop": 8,
  "paddingRight": 6,
  "paddingBottom": 8,
  "paddingLeft": 6,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 6,
  "borderTopLeftRadius": 6,
  "borderTopRightRadius": 6,
  "borderBottomRightRadius": 6,
  "borderBottomLeftRadius": 6,
  "minWidth": 0,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "width": "33.3333%"
 },
 "view#app__scrollview#view__view.screen__view.text-menu__view.tile__text.tt-name": {
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold",
  "maxWidth": "100%",
  "lineHeight": 16,
  "marginBottom": 3,
  "width": "100%",
  "textAlign": "center"
 },
 "view#app__scrollview#view__view.screen__view.text-menu__view.tile__text.tt-sub": {
  "color": "#7a849b",
  "fontSize": 11,
  "minHeight": 12,
  "maxWidth": "100%",
  "lineHeight": 15,
  "marginBottom": 3,
  "width": "100%",
  "textAlign": "center"
 },
 "view#app__scrollview#view__view.screen__text.hint.mt2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 10,
  "lineHeight": 19,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__text.grid-title": {
  "color": "#7a849b",
  "fontSize": 11,
  "letterSpacing": 2,
  "marginTop": 14,
  "marginRight": 2,
  "marginBottom": 10,
  "marginLeft": 2,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isxhq2htm.text-rows": {
  "color": "#e9edf6",
  "fontSize": 15,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card.isxhq2htm.text-rows__view.row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 7,
  "paddingRight": 0,
  "paddingBottom": 7,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.isxhq2htm.text-rows__view.row__text.rk": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "marginRight": 10,
  "__textW": 72
 },
 "view#app__scrollview#view__view.screen__view.card.isxhq2htm.text-rows__view.row__text.rv": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flex": 1,
  "textAlign": "right",
  "fontWeight": "bold",
  "whiteSpace": "nowrap",
  "minWidth": 0,
  "maxWidth": "62%",
  "textOverflow": "ellipsis",
  "marginRight": 10,
  "__textW": 104
 },
 "view#app__scrollview#view__view.screen__view.card.isxhq2htm.text-rows__view.row__text.rs": {
  "color": "#7a849b",
  "fontSize": 11,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 24
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 4,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 6,
  "paddingRight": 0,
  "paddingBottom": 6,
  "paddingLeft": 0,
  "borderBottomWidth": 0,
  "borderBottomColor": "#ffffff0d",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line__text.il-k": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "marginRight": 10,
  "__textW": 48
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line__text.il-v": {
  "color": "#e6b64c",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 10,
  "__textW": 65
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line__text.il-s": {
  "color": "#7a849b",
  "fontSize": 11,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 200
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginRight": 10,
  "__textW": 23
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line__text.il-k.isxmg8sha": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "marginRight": 10,
  "__textW": 48
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line__text.il-r": {
  "color": "#e9edf6",
  "fontSize": 12,
  "textAlign": "right",
  "whiteSpace": "nowrap",
  "minWidth": 0,
  "maxWidth": "78%",
  "textOverflow": "ellipsis",
  "marginRight": 10,
  "__textW": 66
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line.idle-mini": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 6,
  "paddingRight": 0,
  "paddingBottom": 6,
  "paddingLeft": 0,
  "borderBottomWidth": 0,
  "borderBottomColor": "#ffffff0d",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line.idle-mini__text.il-k": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "marginRight": 10,
  "__textW": 48
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.idle-line.idle-mini__text.il-s": {
  "color": "#7a849b",
  "fontSize": 11,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 299
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.btn-row.mt2": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginTop": 10,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.btn-row.mt2__text.btn.ghost.small": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 12,
  "paddingBottom": 0,
  "paddingLeft": 12,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "transparent",
  "fontWeight": "bold",
  "minWidth": 86,
  "flex": 1,
  "whiteSpace": "normal",
  "textAlign": "center",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "lineHeight": 15,
  "marginRight": 10,
  "__textW": 48
 },
 "view#app__scrollview#view__view.screen__view.card.idle-card__view.btn-row.mt2__text.btn.primary": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 12,
  "paddingBottom": 0,
  "paddingLeft": 12,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#e05a6d40",
  "backgroundColor": "#c9364a",
  "fontWeight": "bold",
  "flex": 1,
  "minWidth": 86,
  "whiteSpace": "normal",
  "textAlign": "center",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "lineHeight": 16,
  "marginRight": 10,
  "__textW": 85
 },
 "view#app__view#navbar": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%",
  "maxWidth": 520,
  "flexDirection": "row",
  "backgroundColor": "rgba(12,15,23,.96)",
  "borderTopWidth": 1,
  "borderTopColor": "#232b3b",
  "paddingBottom": 0,
  "height": 62,
  "flex": 0
 },
 "view#app__view#navbar__view.active.nav-item": {
  "color": "#e6b64c",
  "fontSize": 11,
  "flex": 1,
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center"
 },
 "view#app__view#navbar__view.active.nav-item__text.ico": {
  "color": "#e6b64c",
  "fontSize": 19,
  "lineHeight": 19,
  "marginBottom": 3,
  "width": "100%",
  "textAlign": "center"
 },
 "view#app__view#navbar__view.active.nav-item__text.nav-t": {
  "color": "#e6b64c",
  "fontSize": 11,
  "marginBottom": 3,
  "width": "100%",
  "textAlign": "center"
 },
 "view#app__view#navbar__view.nav-item": {
  "color": "#7a849b",
  "fontSize": 11,
  "flex": 1,
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center"
 },
 "view#app__view#navbar__view.nav-item__text.ico": {
  "color": "#7a849b",
  "fontSize": 19,
  "lineHeight": 19,
  "marginBottom": 3,
  "width": "100%",
  "textAlign": "center"
 },
 "view#app__view#navbar__view.nav-item__text.nav-t": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginBottom": 3,
  "width": "100%",
  "textAlign": "center"
 },
 "view#app__view#modal-root": {
  "color": "#e9edf6",
  "fontSize": 15,
  "position": "absolute",
  "left": 0,
  "top": 0,
  "right": 0,
  "bottom": 0
 },
 "view#app__view#modal-root__view.modal-mask": {
  "color": "#e9edf6",
  "fontSize": 15,
  "position": "absolute",
  "backgroundColor": "rgba(0,0,0,.62)",
  "left": 0,
  "top": 0,
  "right": 0,
  "bottom": 0
 },
 "view#app__view#modal-root__view.center.sheet": {
  "color": "#e9edf6",
  "fontSize": 15,
  "position": "absolute",
  "width": "92%",
  "maxWidth": 520,
  "maxHeight": "86%",
  "backgroundColor": "#0b0e15",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderBottomWidth": 0,
  "borderTopLeftRadius": 18,
  "borderTopRightRadius": 18,
  "borderBottomRightRadius": 18,
  "borderBottomLeftRadius": 18,
  "flexDirection": "column",
  "paddingBottom": 0,
  "borderRadius": 18,
  "left": 0,
  "bottom": 0
 },
 "view#app__view#modal-root__view.center.sheet__view.sheet-head": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 14,
  "paddingRight": 18,
  "paddingBottom": 12,
  "paddingLeft": 18,
  "borderBottomWidth": 1,
  "borderBottomColor": "#232b3b"
 },
 "view#app__view#modal-root__view.center.sheet__view.sheet-head__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginRight": 10,
  "__textW": 60
 },
 "view#app__view#modal-root__view.center.sheet__view.sheet-head__view.close-x": {
  "color": "#7a849b",
  "fontSize": 15,
  "width": 34,
  "height": 34,
  "flex": 0,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "backgroundColor": "#111621",
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "padding": 0,
  "paddingTop": 0,
  "paddingRight": 0,
  "paddingBottom": 0,
  "paddingLeft": 0,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "lineHeight": 15,
  "marginRight": 10
 },
 "view#app__view#modal-root__view.center.sheet__view.sheet-head__view.close-x__text.ce-ico": {
  "color": "#7a849b",
  "fontSize": 15,
  "lineHeight": 15,
  "__textW": 8
 },
 "view#app__view#modal-root__view.center.sheet__text.sheet-body": {
  "color": "#e9edf6",
  "fontSize": 15,
  "paddingTop": 14,
  "paddingRight": 18,
  "paddingBottom": 18,
  "paddingLeft": 18,
  "width": "100%"
 },
 "view#app__view#modal-root__view.page": {
  "color": "#e9edf6",
  "fontSize": 15,
  "position": "absolute",
  "width": "100%",
  "maxWidth": 520,
  "backgroundColor": "#0b0e15",
  "flexDirection": "column",
  "top": 0,
  "bottom": 0,
  "left": "50%"
 },
 "view#app__view#modal-root__view.page__view.page-head": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 8,
  "paddingRight": 14,
  "paddingBottom": 10,
  "paddingLeft": 14,
  "borderBottomWidth": 1,
  "borderBottomColor": "#232b3b",
  "backgroundColor": "rgba(9,12,18,.96)"
 },
 "view#app__view#modal-root__view.page__view.page-head__view.back-x": {
  "color": "#b6bfd0",
  "fontSize": 20,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "padding": 0,
  "paddingTop": 0,
  "paddingRight": 0,
  "paddingBottom": 0,
  "paddingLeft": 0,
  "width": 40,
  "height": 40,
  "flex": 0,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "backgroundColor": "#111621",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "lineHeight": 20,
  "marginRight": 10
 },
 "view#app__view#modal-root__view.page__view.page-head__view.back-x__text.ce-ico": {
  "color": "#b6bfd0",
  "fontSize": 20,
  "lineHeight": 20,
  "__textW": 8
 },
 "view#app__view#modal-root__view.page__view.page-head__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginRight": 10,
  "__textW": 60
 },
 "view#app__view#modal-root__view.page__view.page-head__view.page-pad": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": 40,
  "flex": 0,
  "marginRight": 10
 },
 "view#app__view#modal-root__view.page__view.sheet-body": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minHeight": 0,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 24,
  "paddingLeft": 14
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas": {
  "color": "#e9edf6",
  "fontSize": 15,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view": {
  "color": "#e9edf6",
  "fontSize": 15
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view__text.sub": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__text.note": {
  "color": "#7a849b",
  "fontSize": 12,
  "lineHeight": 21,
  "width": "100%"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view.bar.exp.mt3": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginTop": 14,
  "height": 8,
  "backgroundColor": "#0d1120",
  "borderRadius": 6,
  "borderTopLeftRadius": 6,
  "borderTopRightRadius": 6,
  "borderBottomRightRadius": 6,
  "borderBottomLeftRadius": 6
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view.bar.exp.mt3__view.isx1mfx3mc": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "0%"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view.kv": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "space-between",
  "paddingTop": 5,
  "paddingRight": 0,
  "paddingBottom": 5,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view.kv__text.k": {
  "color": "#7a849b",
  "fontSize": 13,
  "flex": 0,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 75
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card.isxmw2bas__view.kv__text": {
  "color": "#e9edf6",
  "fontSize": 13,
  "marginRight": 10,
  "__textW": 58
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__view.kv": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "space-between",
  "paddingTop": 5,
  "paddingRight": 0,
  "paddingBottom": 5,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__view.kv__text.k": {
  "color": "#7a849b",
  "fontSize": 13,
  "flex": 0,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 175
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__view.kv__text.isxmq1bso": {
  "color": "#e6b64c",
  "fontSize": 13,
  "marginRight": 10,
  "__textW": 41
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__view.kv__text": {
  "color": "#e9edf6",
  "fontSize": 13,
  "marginRight": 10,
  "__textW": 86
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__text.hint.mb2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginBottom": 10,
  "lineHeight": 19,
  "width": "100%"
 },
 "view#app__view#modal-root__view.page__view.sheet-body__view.card__view.kv__text.isx184nt68": {
  "color": "#e9edf6",
  "fontSize": 13,
  "whiteSpace": "nowrap",
  "marginRight": 10,
  "__textW": 124
 },
 "view#app__view#battle-root": {
  "color": "#e9edf6",
  "fontSize": 15,
  "position": "absolute",
  "left": 0,
  "top": 0,
  "right": 0,
  "bottom": 0
 },
 "view#app__view#battle-root__view.b-head": {
  "color": "#e9edf6",
  "fontSize": 15
 },
 "view#app__view#battle-root__view.b-head__text.b-title": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__view#battle-root__view.b-head__text.btn.ghost.small": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "transparent",
  "fontWeight": "bold",
  "minWidth": 44,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "width": "100%"
 },
 "view#app__view#battle-root__view.b-field": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "flexDirection": "column",
  "paddingTop": 0,
  "paddingRight": 14,
  "paddingBottom": 0,
  "paddingLeft": 14
 },
 "view#app__view#battle-root__view.b-field__view.b-row.enemies": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "justifyContent": "center",
  "flexWrap": "wrap"
 },
 "view#app__view#battle-root__view.b-field__text.b-line-label": {
  "color": "#7a849b",
  "fontSize": 11,
  "textAlign": "center",
  "letterSpacing": 1,
  "width": "100%"
 },
 "view#app__view#battle-root__view.b-field__view.allies.b-row.back": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "justifyContent": "center",
  "flexWrap": "wrap"
 },
 "view#app__view#battle-root__view.b-field__view.allies.b-row.front": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "justifyContent": "center",
  "flexWrap": "wrap"
 },
 "view#app__view#battle-root__view#battle-log": {
  "color": "#7a849b",
  "fontSize": 11,
  "height": 86,
  "marginTop": 8,
  "marginRight": 14,
  "marginBottom": 8,
  "marginLeft": 14,
  "paddingTop": 8,
  "paddingRight": 12,
  "paddingBottom": 8,
  "paddingLeft": 12,
  "backgroundColor": "#00000066",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10
 },
 "view#app__view#battle-root__view.b-controls": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "column",
  "paddingTop": 0,
  "paddingRight": 14,
  "paddingBottom": 12,
  "paddingLeft": 14
 },
 "view#app__view#battle-root__view.b-controls__view.b-potions": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "column",
  "marginBottom": 8
 },
 "view#app__view#battle-root__view.b-controls__text.block.btn": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 18,
  "paddingBottom": 0,
  "paddingLeft": 18,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "backgroundColor": "#161d2a",
  "fontWeight": "bold",
  "width": "100%",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "marginBottom": 8
 },
 "view#app__scrollview#view__view.screen__view.card__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card__view.t1__text.t1-t": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 90
 },
 "view#app__scrollview#view__view.screen__view.card__view.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18
 },
 "view#app__scrollview#view__view.screen__view.card__view.t2__text.t2-t": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.section-title": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "fontWeight": "bold",
  "letterSpacing": 1,
  "marginTop": 18,
  "marginRight": 4,
  "marginBottom": 10,
  "marginLeft": 4
 },
 "view#app__scrollview#view__view.screen__view.section-title__text.section-title-t": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "fontWeight": "bold",
  "letterSpacing": 1,
  "marginRight": 10,
  "__textW": 60
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 10,
  "paddingRight": 4,
  "paddingBottom": 10,
  "paddingLeft": 4,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row__view.grow__view.t1__text.t1-t": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 45
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row__view.grow__view.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row__view.grow__view.t2__text.t2-t": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1lwcmvy.list-row__text.chev": {
  "color": "#7a849b",
  "fontSize": 16,
  "flex": 0,
  "alignSelf": "center",
  "lineHeight": 16,
  "marginRight": 14,
  "__textW": 9
 },
 "view#app__scrollview#view__view.screen__view.blk.hint.mt2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 10,
  "width": "100%",
  "lineHeight": 19
 },
 "view#app__scrollview#view__view.screen__view.blk.hint.mt2__text.blk.hint-t": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 19,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "padding": 0,
  "paddingTop": 10,
  "paddingRight": 4,
  "paddingBottom": 10,
  "paddingLeft": 4,
  "flexDirection": "row",
  "alignItems": "center",
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row__view.grow__view.t1__text.t1-t": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 45
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row__view.grow__view.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row__view.grow__view.t2__text.t2-t": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx__view.isxv4i8ee.list-row__text.chev": {
  "color": "#7a849b",
  "fontSize": 16,
  "flex": 0,
  "alignSelf": "center",
  "lineHeight": 16,
  "marginRight": 14,
  "__textW": 9
 },
 "view#app__scrollview#view__view.screen__view.btn-row.mt2": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginTop": 10,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.btn-row.mt2__view.block.btn.off.primary": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 12,
  "paddingBottom": 0,
  "paddingLeft": 12,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#e05a6d40",
  "backgroundColor": "#c9364a",
  "fontWeight": "bold",
  "width": "100%",
  "flex": 1,
  "minWidth": 86,
  "whiteSpace": "normal",
  "textAlign": "center",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "lineHeight": 16,
  "marginRight": 10
 },
 "view#app__scrollview#view__view.screen__view.btn-row.mt2__view.block.btn.off.primary__text.btn-t": {
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold",
  "lineHeight": 16,
  "textAlign": "center",
  "whiteSpace": "normal",
  "marginRight": 6,
  "__textW": 105
 },
 "view#app__scrollview#view__view.screen__text.blk.hint.mt2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 10,
  "width": "100%",
  "lineHeight": 19
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "borderColor": "#232b3b",
  "opacity": 0.55,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__text.world-ico": {
  "color": "#e9edf6",
  "fontSize": 24,
  "width": 52,
  "height": 52,
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "backgroundColor": "#232c42",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "lineHeight": 24,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__view.grow__view.t1__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 30
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__view.grow__view.t1__text.tag": {
  "color": "#b6bfd0",
  "fontSize": 11,
  "fontWeight": "normal",
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 1,
  "paddingRight": 6,
  "paddingBottom": 1,
  "paddingLeft": 6,
  "alignSelf": "center",
  "lineHeight": 15,
  "marginRight": 6,
  "__textW": 44
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__view.grow__text.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isxa4xx1i.locked.world-card__text.chev": {
  "color": "#7a849b",
  "fontSize": 16,
  "flex": 0,
  "alignSelf": "center",
  "lineHeight": 16,
  "marginRight": 12,
  "__textW": 9
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx.world-card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx.world-card__text.world-ico": {
  "color": "#e9edf6",
  "fontSize": 24,
  "width": 52,
  "height": 52,
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "backgroundColor": "#232c42",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "lineHeight": 24,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx.world-card__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx.world-card__view.grow__text.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx.world-card__view.grow__text.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1runjyx.world-card__text.chev": {
  "color": "#7a849b",
  "fontSize": 16,
  "flex": 0,
  "alignSelf": "center",
  "lineHeight": 16,
  "marginRight": 12,
  "__textW": 9
 },
 "view#app__scrollview#view__view.screen__view.card.isxc7pc6b.world-card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "opacity": 0.45,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card.isxc7pc6b.world-card__text.world-ico": {
  "color": "#e9edf6",
  "fontSize": 24,
  "width": 52,
  "height": 52,
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "backgroundColor": "#232c42",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "lineHeight": 24,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isxc7pc6b.world-card__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isxc7pc6b.world-card__view.grow__text.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isxc7pc6b.world-card__view.grow__text.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isxc7pc6b.world-card__text.chev": {
  "color": "#7a849b",
  "fontSize": 16,
  "flex": 0,
  "alignSelf": "center",
  "lineHeight": 16,
  "marginRight": 12,
  "__textW": 9
 },
 "view#app__scrollview#view__view.screen__view.card__view": {
  "color": "#e9edf6",
  "fontSize": 15
 },
 "view#app__scrollview#view__view.screen__view.card__view__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view__text.sub": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid": {
  "color": "#e9edf6",
  "fontSize": 15
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.pos-row-label": {
  "color": "#e9edf6",
  "fontSize": 12,
  "marginTop": 8,
  "marginRight": 2,
  "marginBottom": 6,
  "marginLeft": 2,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.pos-row-label__text": {
  "color": "#e9edf6",
  "fontSize": 12,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 236
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.filled.protag-slot.pslot": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#e6b64c12",
  "borderWidth": 1,
  "borderColor": "#e6b64c",
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "minHeight": 96,
  "padding": 10,
  "paddingTop": 10,
  "paddingRight": 10,
  "paddingBottom": 10,
  "paddingLeft": 10,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 10
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.filled.protag-slot.pslot__text.isxmq1bso.pos-tag": {
  "color": "#7a849b",
  "fontSize": 11,
  "position": "absolute",
  "top": 6,
  "left": 8,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.filled.protag-slot.pslot__text.avatar.isx1nwqca7": {
  "color": "#e6b64c",
  "fontSize": 17.6,
  "borderColor": "#e6b64c",
  "width": 40,
  "height": 40,
  "backgroundColor": "#232c42",
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "fontWeight": "bold",
  "flex": 1,
  "marginTop": 8,
  "marginRight": 0,
  "marginBottom": 4,
  "marginLeft": 0,
  "borderRadius": 20
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.filled.protag-slot.pslot__text.pname": {
  "color": "#e9edf6",
  "fontSize": 13,
  "textAlign": "center",
  "fontWeight": "bold",
  "minWidth": 0,
  "whiteSpace": "nowrap",
  "textOverflow": "ellipsis",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.filled.protag-slot.pslot__text.pmeta": {
  "color": "#7a849b",
  "fontSize": 11,
  "textAlign": "center",
  "minWidth": 0,
  "whiteSpace": "nowrap",
  "textOverflow": "ellipsis",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.pslot": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#161d2a",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "minHeight": 96,
  "padding": 10,
  "paddingTop": 10,
  "paddingRight": 10,
  "paddingBottom": 10,
  "paddingLeft": 10,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 10
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.pslot__text.pos-tag": {
  "color": "#7a849b",
  "fontSize": 11,
  "position": "absolute",
  "top": 6,
  "left": 8,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.party-grid__view.party-slots__view.pslot__text.isx1xgut5": {
  "color": "#7a849b",
  "fontSize": 12,
  "textAlign": "center",
  "paddingTop": 34,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__text.block.btn.mt3.small": {
  "color": "#e9edf6",
  "fontSize": 12,
  "marginTop": 14,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "backgroundColor": "#161d2a",
  "fontWeight": "bold",
  "minWidth": 44,
  "width": "100%",
  ":active": {
   "backgroundColor": "#1d2534"
  }
 },
 "view#app__scrollview#view__view.screen__view.card__view.btn-grid3.mt2": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginTop": 10,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card__view.btn-grid3.mt2__text.btn.ghost.small": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "transparent",
  "fontWeight": "bold",
  "minWidth": 44,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "width": "33.3333%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.btn-grid3.mt1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginTop": 4,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card__view.btn-grid3.mt1__text.btn.gold.small": {
  "color": "#fdf3dc",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#e6b64c44",
  "backgroundColor": "#b98d2a",
  "fontWeight": "bold",
  "minWidth": 44,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "width": "33.3333%"
 },
 "view#app__scrollview#view__view.screen__view.card__text.hint.mt1": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 4,
  "lineHeight": 19,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "borderColor": "#e6b64c55",
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 10,
  "paddingRight": 4,
  "paddingBottom": 10,
  "paddingLeft": 4,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__text.avatar.isx1nwqca7": {
  "color": "#e6b64c",
  "fontSize": 17.6,
  "borderColor": "#e6b64c",
  "width": 40,
  "height": 40,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__view.grow__view.t1__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 30
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__view.grow__view.t1__text.isxc4hjzl.tag": {
  "color": "#b6bfd0",
  "fontSize": 11,
  "fontWeight": "normal",
  "borderColor": "#333e55",
  "borderWidth": 1,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 1,
  "paddingRight": 6,
  "paddingBottom": 1,
  "paddingLeft": 6,
  "alignSelf": "center",
  "lineHeight": 15,
  "marginRight": 6,
  "__textW": 22
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__view.grow__view.t1__text.tag": {
  "color": "#b6bfd0",
  "fontSize": 11,
  "fontWeight": "normal",
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 1,
  "paddingRight": 6,
  "paddingBottom": 1,
  "paddingLeft": 6,
  "alignSelf": "center",
  "lineHeight": 15,
  "marginRight": 6,
  "__textW": 22
 },
 "view#app__scrollview#view__view.screen__view.card__view.isxc5zrlg.list-row__view.grow__text.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__text.empty": {
  "color": "#7a849b",
  "fontSize": 13,
  "textAlign": "center",
  "paddingTop": 30,
  "paddingRight": 0,
  "paddingBottom": 30,
  "paddingLeft": 0,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__text.block.btn.mt3.primary": {
  "color": "#e9edf6",
  "fontSize": 13,
  "marginTop": 14,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 18,
  "paddingBottom": 0,
  "paddingLeft": 18,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#e05a6d40",
  "backgroundColor": "#c9364a",
  "fontWeight": "bold",
  "width": "100%",
  ":active": {
   "backgroundColor": "#1d2534"
  }
 },
 "view#app__scrollview#view__view.screen__view.card__view.kv": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "space-between",
  "paddingTop": 5,
  "paddingRight": 0,
  "paddingBottom": 5,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__scrollview#view__view.screen__view.card__view.kv__text.k": {
  "color": "#7a849b",
  "fontSize": 13,
  "flex": 0,
  "minWidth": 0,
  "marginRight": 10,
  "__textW": 30
 },
 "view#app__scrollview#view__view.screen__view.card__view.kv__text": {
  "color": "#e9edf6",
  "fontSize": 13,
  "marginRight": 10,
  "__textW": 8
 },
 "view#app__scrollview#view__view.screen__view.card__view.kv__text.isx13m278j": {
  "color": "#56c894",
  "fontSize": 13,
  "marginRight": 10,
  "__textW": 15
 },
 "view#app__scrollview#view__view.screen__view.card__view.formation-list": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginTop": 8,
  "borderTopWidth": 1,
  "borderTopColor": "#232b3b"
 },
 "view#app__scrollview#view__view.screen__view.card__view.formation-list__view.fm-row": {
  "color": "#e9edf6",
  "fontSize": 11,
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap",
  "paddingTop": 6,
  "paddingRight": 0,
  "paddingBottom": 6,
  "paddingLeft": 0,
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff08",
  "opacity": 0.55
 },
 "view#app__scrollview#view__view.screen__view.card__view.formation-list__view.fm-row__text.fm-name": {
  "color": "#e9edf6",
  "fontSize": 11,
  "fontWeight": "bold",
  "minWidth": 62,
  "marginRight": 6,
  "__textW": 45
 },
 "view#app__scrollview#view__view.screen__view.card__view.formation-list__view.fm-row__text.fm-req": {
  "color": "#7a849b",
  "fontSize": 11,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 6,
  "__textW": 115
 },
 "view#app__scrollview#view__view.screen__view.card__view.formation-list__view.fm-row__text.fm-buff": {
  "color": "#56c894",
  "fontSize": 11,
  "flex": 0,
  "whiteSpace": "nowrap",
  "marginRight": 6,
  "__textW": 136
 },
 "view#app__scrollview#view__view.screen__view.card__view.formation-list__view.fm-row__view.fm-on": {
  "color": "#56c894",
  "fontSize": 11,
  "flex": 0,
  "width": 46,
  "textAlign": "right",
  "marginRight": 6
 },
 "view#app__scrollview#view__view.screen__view.pill-tabs": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "paddingBottom": 6
 },
 "view#app__scrollview#view__view.screen__view.pill-tabs__text.active.pill": {
  "color": "#fff",
  "fontSize": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 8,
  "paddingRight": 14,
  "paddingBottom": 8,
  "paddingLeft": 14,
  "minHeight": 44,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#d43a4f",
  "backgroundColor": "#d43a4f22",
  "marginRight": 6,
  "__textW": 24
 },
 "view#app__scrollview#view__view.screen__view.pill-tabs__text.pill": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 8,
  "paddingRight": 14,
  "paddingBottom": 8,
  "paddingLeft": 14,
  "minHeight": 44,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "marginRight": 6,
  "__textW": 13
 },
 "view#app__scrollview#view__view.screen__view.filter-bar": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "alignItems": "center",
  "marginBottom": 8
 },
 "view#app__scrollview#view__view.screen__view.filter-bar__text.flabel": {
  "color": "#7a849b",
  "fontSize": 11,
  "flex": 0,
  "marginRight": 8,
  "__textW": 22
 },
 "view#app__scrollview#view__view.screen__view.filter-bar__view.grow-pills.pill-tabs": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "paddingBottom": 0,
  "flex": 1,
  "marginBottom": 0,
  "marginRight": 8
 },
 "view#app__scrollview#view__view.screen__view.filter-bar__view.grow-pills.pill-tabs__text.active.pill": {
  "color": "#fff",
  "fontSize": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 8,
  "paddingRight": 14,
  "paddingBottom": 8,
  "paddingLeft": 14,
  "minHeight": 44,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#d43a4f",
  "backgroundColor": "#d43a4f22",
  "marginRight": 6,
  "__textW": 24
 },
 "view#app__scrollview#view__view.screen__view.filter-bar__view.grow-pills.pill-tabs__text.pill": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 8,
  "paddingRight": 14,
  "paddingBottom": 8,
  "paddingLeft": 14,
  "minHeight": 44,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "marginRight": 6,
  "__textW": 48
 },
 "view#app__scrollview#view__view.screen__view.filter-bar__view.search-input#char-search": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flex": 1,
  "minHeight": 44,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 0,
  "paddingRight": 12,
  "paddingBottom": 0,
  "paddingLeft": 12,
  "marginRight": 8,
  "__textW": 53
 },
 "view#app__scrollview#view__view.screen__view.filter-bar__text.btn.ghost.small": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "transparent",
  "fontWeight": "bold",
  "minWidth": 44,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "marginRight": 8,
  "__textW": 37
 },
 "view#app__scrollview#view__view.screen__text.isxao4oo7": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 0,
  "marginRight": 2,
  "marginBottom": 8,
  "marginLeft": 2,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.char-grid#char-list": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.char-grid#char-list__text.empty.isx10ihlmm": {
  "color": "#7a849b",
  "fontSize": 13,
  "textAlign": "center",
  "paddingTop": 30,
  "paddingRight": 0,
  "paddingBottom": 30,
  "paddingLeft": 0,
  "width": "33.3333%"
 },
 "view#app__scrollview#view__view.screen__view.char-grid#char-list__text.block.btn.isx10ihlmm.primary": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 18,
  "paddingBottom": 0,
  "paddingLeft": 18,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#e05a6d40",
  "backgroundColor": "#c9364a",
  "fontWeight": "bold",
  "width": "33.3333%",
  ":active": {
   "backgroundColor": "#1d2534"
  }
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 11,
  "paddingRight": 14,
  "paddingBottom": 11,
  "paddingLeft": 14,
  "marginBottom": 14,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain__text.gr-ico": {
  "color": "#e9edf6",
  "fontSize": 22,
  "flex": 0,
  "opacity": 0.92,
  "marginRight": 14,
  "__textW": 12
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain__view.gr-grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain__view.gr-grow__text.gr-t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain__view.gr-grow__text.gr-t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 17,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain__text.gr-cur": {
  "color": "#e6b64c",
  "fontSize": 12,
  "flex": 0,
  "textAlign": "right",
  "maxWidth": "42%",
  "marginRight": 14,
  "__textW": 36
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain.tap": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 11,
  "paddingRight": 14,
  "paddingBottom": 11,
  "paddingLeft": 14,
  "marginBottom": 14,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain.tap__text.gr-ico": {
  "color": "#e9edf6",
  "fontSize": 22,
  "flex": 0,
  "opacity": 0.92,
  "marginRight": 14,
  "__textW": 12
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain.tap__view.gr-grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain.tap__view.gr-grow__text.gr-t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain.tap__view.gr-grow__text.gr-t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 17,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.grow-row.plain.tap__text.gr-cur": {
  "color": "#e6b64c",
  "fontSize": 12,
  "flex": 0,
  "textAlign": "right",
  "maxWidth": "42%",
  "marginRight": 14,
  "__textW": 25
 },
 "view#app__scrollview#view__view.screen__view.tab-cards": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "paddingTop": 10,
  "paddingRight": 0,
  "paddingBottom": 10,
  "paddingLeft": 0,
  "marginBottom": 10,
  "backgroundColor": "#0b0e15f5"
 },
 "view#app__scrollview#view__view.screen__view.tab-cards__text.active.tab-card": {
  "color": "#fff",
  "fontSize": 12,
  "flex": 1,
  "minWidth": 0,
  "minHeight": 44,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "borderWidth": 1,
  "borderColor": "#d43a4f",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "backgroundColor": "#d43a4f22",
  "fontWeight": "bold",
  "marginRight": 10,
  "__textW": 24
 },
 "view#app__scrollview#view__view.screen__view.tab-cards__text.tab-card": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 1,
  "minWidth": 0,
  "minHeight": 44,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "backgroundColor": "#111621",
  "fontWeight": "bold",
  "marginRight": 10,
  "__textW": 24
 },
 "view#app__scrollview#view__view.screen__view.card.mb3": {
  "color": "#e9edf6",
  "fontSize": 15,
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-head": {
  "color": "#e9edf6",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "marginBottom": 8
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-head__text": {
  "color": "#e9edf6",
  "fontSize": 12,
  "marginRight": 8,
  "__textW": 45
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-head__text.sub": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginRight": 8,
  "__textW": 36
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flexDirection": "row",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid__view.bg-slot.filled": {
  "color": "#e9edf6",
  "fontSize": 15,
  "minHeight": 62,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#161d2a",
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "flex-start",
  "paddingTop": 5,
  "paddingRight": 6,
  "paddingBottom": 11,
  "paddingLeft": 6,
  "textAlign": "center",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "width": "20.0000%"
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid__view.bg-slot.filled__text.bg-name": {
  "color": "#e9edf6",
  "fontSize": 13,
  "textAlign": "center",
  "width": "100%",
  "flex": 1,
  "marginTop": 0,
  "marginRight": 0,
  "marginBottom": 2,
  "marginLeft": 0,
  "fontWeight": "bold",
  "wordBreak": "break-all",
  "maxHeight": 33,
  "lineHeight": 16
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid__view.bg-slot.filled__text.bg-count": {
  "color": "#e6b64c",
  "fontSize": 12,
  "textAlign": "center",
  "fontWeight": "bold",
  "marginBottom": 2,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid__view.bg-slot": {
  "color": "#e9edf6",
  "fontSize": 15,
  "minHeight": 62,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#00000022",
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "flex-start",
  "paddingTop": 5,
  "paddingRight": 6,
  "paddingBottom": 11,
  "paddingLeft": 6,
  "textAlign": "center",
  "width": "20.0000%"
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid__view.add.bg-slot": {
  "color": "#7a849b",
  "fontSize": 22,
  "minHeight": 62,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "borderWidth": 1,
  "borderColor": "#333e55",
  "backgroundColor": "transparent",
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center",
  "paddingTop": 5,
  "paddingRight": 6,
  "paddingBottom": 11,
  "paddingLeft": 6,
  "textAlign": "center",
  ":active": {
   "backgroundColor": "#ffd76a22"
  },
  "lineHeight": 22,
  "width": "20.0000%"
 },
 "view#app__scrollview#view__view.screen__view.card.mb3__view.bg-grid__view.add.bg-slot__text": {
  "color": "#7a849b",
  "fontSize": 22,
  "lineHeight": 22,
  "textAlign": "center",
  "marginBottom": 2,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.mb2.pill-tabs.tight": {
  "color": "#e9edf6",
  "fontSize": 15,
  "marginBottom": 10,
  "flexDirection": "row",
  "paddingBottom": 0,
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.mb2.pill-tabs.tight__text.active.pill.sm": {
  "color": "#fff",
  "fontSize": 11,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 5,
  "paddingRight": 11,
  "paddingBottom": 5,
  "paddingLeft": 11,
  "minHeight": 34,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#d43a4f",
  "backgroundColor": "#d43a4f22",
  "marginRight": 6,
  "__textW": 22
 },
 "view#app__scrollview#view__view.screen__view.mb2.pill-tabs.tight__text.pill.sm": {
  "color": "#7a849b",
  "fontSize": 11,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "paddingTop": 5,
  "paddingRight": 11,
  "paddingBottom": 5,
  "paddingLeft": 11,
  "minHeight": 34,
  "borderRadius": 999,
  "borderTopLeftRadius": 999,
  "borderTopRightRadius": 999,
  "borderBottomRightRadius": 999,
  "borderBottomLeftRadius": 999,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "marginRight": 6,
  "__textW": 24
 },
 "view#app__scrollview#view__view.screen__view.eq-bar": {
  "color": "#7a849b",
  "fontSize": 11,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.eq-bar__text": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginRight": 8,
  "__textW": 126
 },
 "view#app__scrollview#view__view.screen__view.eq-bar__text.btn.ghost.push.small": {
  "color": "#b6bfd0",
  "fontSize": 12,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 40,
  "paddingTop": 0,
  "paddingRight": 13,
  "paddingBottom": 0,
  "paddingLeft": 13,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "backgroundColor": "transparent",
  "fontWeight": "bold",
  "minWidth": 44,
  "flex": 1,
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "marginRight": 8,
  "__textW": 61
 },
 "view#app__scrollview#view__view.screen__view.hint": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 19
 },
 "view#app__scrollview#view__view.screen__view.text-menu__view.tile__view.tt-name": {
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold",
  "maxWidth": "100%",
  "lineHeight": 16,
  "marginBottom": 3
 },
 "view#app__scrollview#view__view.screen__view.text-menu__view.tile__view.tt-name__text": {
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold",
  "lineHeight": 16,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.text-menu__view.tile__view.tt-name__view.tt-dot": {
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold",
  "lineHeight": 16,
  "width": 6,
  "height": 6,
  "marginLeft": 4,
  "backgroundColor": "#d43a4f",
  "borderRadius": 3
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card": {
  "color": "#e9edf6",
  "fontSize": 15,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14,
  "flexDirection": "row",
  "alignItems": "center"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__text.world-ico": {
  "color": "#e9edf6",
  "fontSize": 24,
  "width": 52,
  "height": 52,
  "borderRadius": 12,
  "borderTopLeftRadius": 12,
  "borderTopRightRadius": 12,
  "borderBottomRightRadius": 12,
  "borderBottomLeftRadius": 12,
  "flex": 0,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "backgroundColor": "#232c42",
  "borderWidth": 1,
  "borderColor": "#232b3b",
  "lineHeight": 24,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 12
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__view.grow__view.t1__text": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 30
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__view.grow__view.t1__text.tag": {
  "color": "#b6bfd0",
  "fontSize": 11,
  "fontWeight": "normal",
  "borderWidth": 1,
  "borderColor": "#333e55",
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "paddingTop": 1,
  "paddingRight": 6,
  "paddingBottom": 1,
  "paddingLeft": 6,
  "alignSelf": "center",
  "lineHeight": 15,
  "marginRight": 6,
  "__textW": 44
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__view.grow__text.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1fjgejf.world-card__text.chev": {
  "color": "#7a849b",
  "fontSize": 16,
  "flex": 0,
  "alignSelf": "center",
  "lineHeight": 16,
  "marginRight": 12,
  "__textW": 9
 },
 "view#app__scrollview#view__view.screen__view.card.isx1lwcmvy.text-rows__view.row__text.isxmq1bso.rv": {
  "color": "#e6b64c",
  "fontSize": 13,
  "flex": 1,
  "textAlign": "right",
  "fontWeight": "bold",
  "whiteSpace": "nowrap",
  "minWidth": 0,
  "maxWidth": "62%",
  "textOverflow": "ellipsis",
  "marginRight": 10,
  "__textW": 154
 },
 "view#app__scrollview#view__view.screen__view.card.isxhq2htm.text-rows__view.row__text.isxmq1bso.rk": {
  "color": "#7a849b",
  "fontSize": 12,
  "flex": 0,
  "marginRight": 10,
  "__textW": 72
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__text.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap",
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card__view.isx1yd8pbd.list-row__view.grow__text.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa": {
  "color": "#e9edf6",
  "fontSize": 15,
  "borderColor": "#232b3b",
  "backgroundColor": "#111621",
  "borderWidth": 1,
  "borderRadius": 10,
  "borderTopLeftRadius": 10,
  "borderTopRightRadius": 10,
  "borderBottomRightRadius": 10,
  "borderBottomLeftRadius": 10,
  "paddingTop": 14,
  "paddingRight": 14,
  "paddingBottom": 14,
  "paddingLeft": 14,
  "marginBottom": 14
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa__view.isxv4i8ee.list-row": {
  "color": "#e9edf6",
  "fontSize": 15,
  "padding": 0,
  "paddingTop": 10,
  "paddingRight": 4,
  "paddingBottom": 10,
  "paddingLeft": 4,
  "flexDirection": "row",
  "alignItems": "center",
  "borderBottomWidth": 1,
  "borderBottomColor": "#ffffff0d"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa__view.isxv4i8ee.list-row__view.grow": {
  "color": "#e9edf6",
  "fontSize": 15,
  "flex": 1,
  "minWidth": 0,
  "marginRight": 14
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa__view.isxv4i8ee.list-row__view.grow__view.t1": {
  "color": "#e9edf6",
  "fontSize": 15,
  "fontWeight": "bold",
  "flexDirection": "row",
  "alignItems": "center",
  "flexWrap": "wrap"
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa__view.isxv4i8ee.list-row__view.grow__view.t1__text.isxmq1bso.t1-t": {
  "color": "#e6b64c",
  "fontSize": 15,
  "fontWeight": "bold",
  "marginRight": 6,
  "__textW": 30
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa__view.isxv4i8ee.list-row__view.grow__view.t2": {
  "color": "#7a849b",
  "fontSize": 11,
  "marginTop": 3,
  "lineHeight": 18
 },
 "view#app__scrollview#view__view.screen__view.card.isx1egwjpa__view.isxv4i8ee.list-row__view.grow__view.t2__text.t2-t": {
  "color": "#7a849b",
  "fontSize": 11,
  "lineHeight": 18,
  "width": "100%"
 },
 "view#app__scrollview#view__view.screen__view.btn-row.mt2__view.block.btn.primary": {
  "color": "#e9edf6",
  "fontSize": 13,
  "flexDirection": "row",
  "alignItems": "center",
  "justifyContent": "center",
  "minHeight": 44,
  "paddingTop": 0,
  "paddingRight": 12,
  "paddingBottom": 0,
  "paddingLeft": 12,
  "borderRadius": 7,
  "borderTopLeftRadius": 7,
  "borderTopRightRadius": 7,
  "borderBottomRightRadius": 7,
  "borderBottomLeftRadius": 7,
  "borderWidth": 1,
  "borderColor": "#e05a6d40",
  "backgroundColor": "#c9364a",
  "fontWeight": "bold",
  "width": "100%",
  "flex": 1,
  "minWidth": 86,
  "whiteSpace": "normal",
  "textAlign": "center",
  ":active": {
   "backgroundColor": "#1d2534"
  },
  "lineHeight": 16,
  "marginRight": 10
 },
 "view#app__scrollview#view__view.screen__view.btn-row.mt2__view.block.btn.primary__text.btn-t": {
  "color": "#e9edf6",
  "fontSize": 13,
  "fontWeight": "bold",
  "lineHeight": 16,
  "textAlign": "center",
  "whiteSpace": "normal",
  "marginRight": 6,
  "__textW": 135
 }
};
